export const API_CALL_REQUEST = "API_CALL_REQUEST";
export const API_CALL_SUCCESS = "API_CALL_SUCCESS";
export const API_CALL_FAILURE = "API_CALL_FAILURE";

export const TASKS_API_CALL_REQUEST = "TASKS_API_CALL_REQUEST";
export const TASKS_API_CALL_SUCCESS = "TASKS_API_CALL_SUCCESS";
export const TASKS_API_CALL_FAILURE = "TASKS_API_CALL_FAILURE";

export const USERS_API_CALL_REQUEST = "USERS_API_CALL_REQUEST";
export const USERS_API_CALL_SUCCESS = "USERS_API_CALL_SUCCESS";
export const USERS_API_CALL_FAILURE = "USERS_API_CALL_FAILURE";

export const USER_DATA_UPDATE = "USER_DATA_UPDATE";
